# Generated by Django 5.0 on 2024-01-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("musicians", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="musician",
            name="instrument_type",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name="musician",
            name="phone_number",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="musician",
            name="email",
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name="musician",
            name="first_name",
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name="musician",
            name="last_name",
            field=models.CharField(default=None, max_length=200),
        ),
    ]
